# Generated by Django 4.2.4 on 2023-08-15 14:47

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bouquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Название букета')),
                ('image', models.ImageField(upload_to='', verbose_name='Картинка')),
                ('price', models.IntegerField(db_index=True, verbose_name='Цена')),
                ('description', models.TextField(max_length=5000, verbose_name='Описание')),
                ('compound', models.TextField(max_length=5000, verbose_name='Состав')),
            ],
            options={
                'verbose_name': 'Букет',
                'verbose_name_plural': 'Букеты',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region=None, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название события')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Цена букета')),
                ('delivery_date', models.DateField(db_index=True, verbose_name='Дата доставки')),
                ('delivery_time', models.IntegerField(verbose_name='Время доставки')),
                ('address', models.CharField(max_length=1000, verbose_name='Адрес доставки')),
                ('comment', models.CharField(blank=True, default='', max_length=1000, verbose_name='Комментарий')),
                ('bouquet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='src.bouquet', verbose_name='Заказанный букет')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='src.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.AddField(
            model_name='bouquet',
            name='events',
            field=models.ManyToManyField(related_name='bouquet', to='src.event', verbose_name='Для событий'),
        ),
    ]
