# Generated by Django 4.2.4 on 2023-08-16 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bouquet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='src.bouquet', verbose_name='Заказанный букет'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='src.client', verbose_name='Клиент'),
        ),
    ]
