# Generated by Django 4.2.4 on 2023-08-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_order_status_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='bouquet',
            name='height',
            field=models.IntegerField(default=30, verbose_name='Высота'),
        ),
        migrations.AddField(
            model_name='bouquet',
            name='width',
            field=models.IntegerField(default=30, verbose_name='Ширина'),
        ),
    ]
