# Generated by Django 4.2.4 on 2023-08-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_bouquet_height_bouquet_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.IntegerField(choices=[(1, 'Как можно скорее'), (2, 'С 10:00 до 12:00'), (2, 'С 12:00 до 14:00'), (2, 'С 14:00 до 16:00'), (2, 'С 16:00 до 18:00'), (2, 'С 18:00 до 20:00')], verbose_name='Время доставки'),
        ),
    ]
