# Generated by Django 4.2.4 on 2023-08-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_rename_delivery_time_order_delivery_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(auto_now_add=True, db_index=True, verbose_name='Дата доставки'),
        ),
    ]
