# Generated by Django 4.2.4 on 2023-08-18 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0008_alter_order_delivery_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActiveOrder',
        ),
        migrations.AlterModelManagers(
            name='order',
            managers=[
            ],
        ),
    ]
